[package]
name = "tutorial1_window"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
winit = { version = "0.29", features = ["rwh_05"] }
env_logger = "0.10"
log = "0.4"
wgpu = "22.0"
